// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package blackjack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HEART-0]
	_ = x[DIAMOND-1]
	_ = x[SPADE-2]
	_ = x[CLUB-3]
}

const _Suit_name = "HEARTDIAMONDSPADECLUB"

var _Suit_index = [...]uint8{0, 5, 12, 17, 21}

func (i Suit) String() string {
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ACE-1]
	_ = x[TWO-2]
	_ = x[THREE-3]
	_ = x[FOUR-4]
	_ = x[FIVE-5]
	_ = x[SIX-6]
	_ = x[SEVEN-7]
	_ = x[EIGHT-8]
	_ = x[NINE-9]
	_ = x[TEN-10]
	_ = x[JACK-11]
	_ = x[QUEEN-12]
	_ = x[KING-13]
}

const _Rank_name = "ACETWOTHREEFOURFIVESIXSEVENEIGHTNINETENJACKQUEENKING"

var _Rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52}

func (i Rank) String() string {
	i -= 1
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
